text = input("Digite algo: ")
print("Tipo primitivo:", type(text))
print("Só tem espaços?", text.isspace())
print("É um número?", text.isnumeric())
print("É alfabético?", text.isalpha())
print("É alfanumérico?", text.isalnum())
print("Está em letras Maiúsculas?", text.isupper())
print("Está em letras Minúsculas?", text.islower())
print("Está capitalizado?", text.istitle())
