n = input("Enter: ")
print("What's your primitive type?", type(n))
print("Only spaces?", n.isspace())
print("Is alphanum?", n.isalnum())
print("Is alpha?", n.isalpha())
print("Is numeric?", n.isnumeric())
print("Is upper?", n.isupper())
print("Is lower?", n.islower())
print("Is capitalize?", n.istitle())
