text = input("Digite algo: ")
print("Tipo primitivo:", type(text))
print("Só tem espaços?", text.isspace())
print("Só tem números?", text.isnumeric())
print("Só tem letras?", text.isalpha())
print("É alfanumérico?", text.isalnum())
print("Só tem letras Maiúsculas?", text.isupper())
print("Só tem letras Minúsculas?", text.islower())
print("Está capitalizado?", text.istitle())
